#181618

$background = rgb(181618)
$foreground = rgb(FDECCA)
$color0 = rgb(434143)
$color1 = rgb(634B4D)
$color2 = rgb(746063)
$color3 = rgb(915A5A)
$color4 = rgb(BE6E5B)
$color5 = rgb(B9743F)
$color6 = rgb(BC974F)
$color7 = rgb(F4DCAC)
$color8 = rgb(AB9A78)
$color9 = rgb(715053)
$color10 = rgb(896E71)
$color11 = rgb(AF6565)
$color12 = rgb(E45A3A)
$color13 = rgb(F79A54)
$color14 = rgb(FAC969)
$color15 = rgb(F4DCAC)
